export default {
    CHANGE_SCALE: 'CHANGE_SCALE',
    TOGGLE_SHOW_GRID: 'TOGGLE_SHOW_GRID',
    TOGGLE_SHOW_ADSORB: 'TOGGLE_SHOW_ADSORB',
    CHANGE_GRID_COLUMN: 'CHANGE_GRID_COLUMN',
    CHANGE_COLOR: 'CHANGE_COLOR',
    TOGGLE_SHOW_ASIDE: 'TOGGLE_SHOW_ASIDE'
}
